USE CollegeDB;
GO

SELECT GETDATE() AS CurrentDateTime;
GO

SELECT CAST(GETDATE() AS DATE) AS CurrentDate;
GO

SELECT YEAR(GETDATE()) AS CurrentYear;
GO

SELECT MONTH(GETDATE()) AS CurrentMonth;
GO

SELECT DAY(GETDATE()) AS CurrentDay;
GO

SELECT DATEADD(DAY, 7, GETDATE()) AS DateAfter7Days;
GO

SELECT DATEADD(MONTH, 1, GETDATE()) AS DateAfter1Month;
GO

SELECT DATEADD(YEAR, 1, GETDATE()) AS DateAfter1Year;
GO

SELECT DATEDIFF(DAY, '2026-01-01', GETDATE()) AS DaysPassed;
GO